### ISSUE TITLE
HTML files need to be updated in image folder

### ISSUE THREAD

**Issue by Gormartsen** [fedberry/fedberry#10]
http://download.fedberry.org/releases/23/images/FedBerry-INSTALL.html

It has wrong download link:
```
SD CARD INSTALLATION

Download images here: http://fedberry.agrez.net
```

**Comment by agrez** [comment]
Should we just delete all the HTML files there? I don't think they are need any more. I only had them with the images when we didn't have a website or github project.

**Comment by Gormartsen** [comment]
:+1: to delete

**Comment by agrez** [comment]
ok, after deleting, maybe we also need to make links to README.md INSTALL.md and RELEASE-NOTES.md a bit more prominent on our website?
