### ISSUE TITLE
Update firmware for Pi3

### ISSUE THREAD

**Issue by GregWildman** [fedberry/fedberry#11]
Can you please update the f23 images with the updated firmware for the Pi3.

Steps I did to boot on a Pi3.

- download latest firmware
``curl -L -o /tmp/raspberry-firmware.zip https://github.com/raspberrypi/firmware/archive/master.zip``

- unpack and copy the following files in the first vfat partition
```
bcm2710-rpi-3-b.dtb
bootcode.bin
fixup*
start*
overlays (complete folder)
```
- Newer firmware flips the LCD screen. Add new config option

`lcd_rotate=2`

**Comment by agrez** [comment]
Support for the RPi 3 in FedBerry was added a few days after its release. These updates are currently residing in our testing repository. New images will be released which will include RPi3 support soon. We plan to upload some FedBerry-23.2 test images (most likely this weekend) that you and others can try out on your RPi 3's (they seem to be running fine on mine thus far).
