### ISSUE TITLE
Koji server to build rpm

### ISSUE THREAD

**Issue by Gormartsen** [fedberry/fedberry#17]
Let's see if I can make it in few days, so @agrez you can get rpms to test if we can have a testing image for FedBerry-Zero

**Comment by agrez** [comment]
I have been waiting for the 4.5.y series kernel as apparently we can enable both armv6 & armv7 support in the single build. (previously we would have to have 2 separate kernels). However, this might be only achievable using mainline at the moment as the bcm2708/09 ports from RPi still seem to be very separate at this point.

Its going to take me some time to re- plumb the kernel.spec with all these changes.

**Comment by mrjoshuap** [comment]
As an FYI, I spoke with a couple people who stated that they use Ansible to assist with the build out of the Koji environment.  Might be worth a look-see.

http://infrastructure.fedoraproject.org/cgit/ansible.git/

**Comment by agrez** [comment]
Closing. Thanks to @Gormartsen we now have http://mock.fedberry.org
