### ISSUE TITLE
How do I build a software using arm(el) architecure?

### ISSUE THREAD

**Issue by guilhermegm** [fedberry/fedberry#18]
Hi, I need to build a C software using arm(el) compiler? Is it possible to compile on rpi (Fedberry)?

This script does not work on hf architecture. =(

Thanks!

**Comment by Gormartsen** [comment]
hi @guilhermegm 
If you upload compiled programs on rpi, it will not work. 
You need to compile it for ARM.

If it does not use any specific instruction x86 related, it should compile as usual.

You upload source code on rpi, you need to make sure that all required libraries installed (in README usually author should mention it).

They you should follow INSTALLATION instructions if provided.

Usually it's something like this:

./configure && make && make install

If you don't have some libraries or forgot to install gcc, make, authconfig and etc ./configure will show what you are messing.

I hope it will help you.

**Comment by guilhermegm** [comment]
The only command provided is:
armv7hl-redhat-linux-gnueabi-gcc -o EvaluationTool main.o

Where I choose the armv7hl-redhat-linux-gnueabi-gcc compiler. But when I use this gcc the compiled program will be 'for' arm(hl) and I need it to be 'for' arm(el).

Is that make sense?

[root@localhost EvaluationTool_SourceCode]# readelf -A EvaluationTool
Attribute Section: aeabi
File Attributes
  Tag_CPU_name: "7-A"
  Tag_CPU_arch: v7
  Tag_CPU_arch_profile: Application
  Tag_ARM_ISA_use: Yes
  Tag_THUMB_ISA_use: Thumb-2
  Tag_FP_arch: VFPv3-D16
  Tag_ABI_PCS_wchar_t: 4
  Tag_ABI_FP_rounding: Needed
  Tag_ABI_FP_denormal: Needed
  Tag_ABI_FP_exceptions: Needed
  Tag_ABI_FP_number_model: IEEE 754
  Tag_ABI_align_needed: 8-byte
  Tag_ABI_align_preserved: 8-byte, except leaf SP
  Tag_ABI_enum_size: int
  Tag_ABI_VFP_args: VFP registers
  Tag_CPU_unaligned_access: v6

[root@localhost EvaluationTool_SourceCode]# readelf -h EvaluationTool
ELF Header:
  Magic:   7f 45 4c 46 01 01 01 00 00 00 00 00 00 00 00 00
  Class:                             ELF32
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              EXEC (Executable file)
  Machine:                           ARM
  Version:                           0x1
  Entry point address:               0x10918
  Start of program headers:          52 (bytes into file)
  Start of section headers:          21860 (bytes into file)
  Flags:                             0x5000402, has entry point, Version5 EABI, hard-float ABI
  Size of this header:               52 (bytes)
  Size of program headers:           32 (bytes)
  Number of program headers:         8
  Size of section headers:           40 (bytes)
  Number of section headers:         36
  Section header string table index: 33

**Comment by Gormartsen** [comment]
Ok, You need to install package gcc-5.3.1-2 on fedberry 
```
dnf install gcc
```
It should provide this file.
There is a list of included files to this package.
http://koji.fedoraproject.org/koji/rpminfo?rpmID=7083538

**Comment by Gormartsen** [comment]
@agrez I am wandering if armv7hl builded with 
```
-mfpu=vfp
-mfloat-abi=hard
```
There is special optimization based on glueabi that works with floating point...
Can you check it out ?

**Comment by Gormartsen** [comment]
@agrez never mind. I checked.
For example here: https://kojipkgs.fedoraproject.org//packages/gcc/5.3.1/2.fc23/data/logs/armv7hl/build.log
echo -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -march=armv7-a -mfpu=vfpv3-d16 -mfloat-abi=hard

@guilhermegm I assume you can build with gcc as well, but you need to compile like this:
```
gcc -mfpu=vfp -mfloat-abi=hard -march=armv7-a -o EvaluationTool main.o
```

**Comment by guilhermegm** [comment]
@Gormartsen 
I tried to compile with those args but still the same problem. Looks like nothing has changed, m'I doing something wrong?

gcc -mfpu=vfp -mfloat-abi=hard -march=armv7-a -o EvaluationTool main.o

[root@unknown EvaluationTool_SourceCode]# readelf -A EvaluationTool
Attribute Section: aeabi
File Attributes
  Tag_CPU_name: "7-A"
  Tag_CPU_arch: v7
  Tag_CPU_arch_profile: Application
  Tag_ARM_ISA_use: Yes
  Tag_THUMB_ISA_use: Thumb-2
  Tag_FP_arch: VFPv3-D16
  Tag_ABI_PCS_wchar_t: 4
  Tag_ABI_FP_rounding: Needed
  Tag_ABI_FP_denormal: Needed
  Tag_ABI_FP_exceptions: Needed
  Tag_ABI_FP_number_model: IEEE 754
  Tag_ABI_align_needed: 8-byte
  Tag_ABI_align_preserved: 8-byte, except leaf SP
  Tag_ABI_enum_size: int
  Tag_ABI_VFP_args: VFP registers
  Tag_CPU_unaligned_access: v6

[root@unknown EvaluationTool_SourceCode]# readelf -h EvaluationTool
ELF Header:
  Magic:   7f 45 4c 46 01 01 01 00 00 00 00 00 00 00 00 00
  Class:                             ELF32
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              EXEC (Executable file)
  Machine:                           ARM
  Version:                           0x1
  Entry point address:               0x10918
  Start of program headers:          52 (bytes into file)
  Start of section headers:          21852 (bytes into file)
  Flags:                             0x5000402, has entry point, Version5 EABI, hard-float ABI
  Size of this header:               52 (bytes)
  Size of program headers:           32 (bytes)
  Number of program headers:         8
  Size of section headers:           40 (bytes)
  Number of section headers:         36
  Section header string table index: 33

**Comment by Gormartsen** [comment]
What kind information you are looking to get from elf headers?

**Comment by guilhermegm** [comment]
I'm looking for the Tag_ABI_VFP_args: VFP registers what says if it's a armhf.

Even if I compile the script to armel I don't know if I can run it on armhf because of the libs.
