### ISSUE TITLE
Kernel Panic mount root FS on first boot 23.2 xfce

### ISSUE THREAD

**Issue by dreamstorpi** [fedberry/fedberry#19]
I downloaded Fedberry XFCE 23.2, installed it to a SD card and booted it on the RPI3. Here's what I get,
PANIC:VFS: Unable to mount root fs on unknown-block(179,3)
and
Entering kbd(current=0xb58d0000, pid1) on processor 2 due to keyboard entry f21kbd>_
Any ideas?

I reformatted the SD card. Wrote it again. Same problem.

**Comment by dreamstorpi** [comment]
I renamed _swap to swap and _/ to /, now I get
PANIC: Attempted to kill exit! exitcode=0x00007f00
Not sure if this adds anything...

**Comment by agrez** [comment]
Thanks for the bug report. A couple of things you can try first:
* Ensure the downloaded raw disk image is not corrupt (ie. check with sha256sum). Refer: https://github.com/fedberry/fedberry/blob/master/INSTALL.md
* Raspberry Pi's can be 'finiky' with certain SD cards. Have you got another SD card to test with? Please check the following site to see if your SD card is referenced: http://elinux.org/RPi_SD_cards

**Comment by dreamstorpi** [comment]
Thanks agrez,

1) I checked the raw image and it is not corrupt
2) I have a Kingston 8GB, class10, SDC10G2/8GB. The list in the wiki shows this mirco SD in its 'ulimate' edition as being OK. I don't have the 'ultimate' edition, so I guess this is my problem. I will try another brand that's in the list and let you know. Could be a few days.

**Comment by agrez** [comment]
I'm not saying its the problem, just that it MIGHT be the problem. Have you tried out another distro using the SD card in question? How about installing Raspbian on the card and see if it works before you go out buying another card to test with.

**Comment by dreamstorpi** [comment]
I tried to install another image on this card. Same issue.
I bought a new one, a Sony SR-8UTY2A/T 8GB and installed Fedberry on it. Booted as it should, user created etc and get to xfce screen.
So issue was clearly the card. Kingston 8GB, class10, SDC10G2/8GB
