### ISSUE TITLE
Provide signed downloads and downloads over HTTPS

### ISSUE THREAD

**Issue by naftulikay** [fedberry/fedberry#22]
For the security-conscious, please provide PGP signatures of your images for the Raspberry Pi alongside TLS support for access to your website.

Providing a checksum over HTTP doesn't do very much in the way of proving authenticity; since a checksum is unkeyed, I have no way of validating that the signature was generated by the owners of the project, and it is trivial to MITM and simply provide a new checksum. Providing PGP signatures (like Fedora proper, Kali Linux, etc.) would allow users to verify that they are downloading the same tarball that the maintainers produced, and sharing the key IDs of the maintainers over HTTPS would create a much higher trust level of image integrity.

**Comment by mrjoshuap** [comment]
I think we just need to incorporate the gpg signing in auto-builds once they have been established.  Still catching up though.

**Comment by agrez** [comment]
Yes, I have been holding off on this bug until we have a build server up and running. Then we can generate some new FedBerry gpg signatures and have everything signed with the new keys.

**Comment by agrez** [comment]
Closing this as we have for some time now provided images over https and also proved signed checksum files.
