### ISSUE TITLE
Problem in ssh login in headless raspberry pi 3

### ISSUE THREAD

**Issue by Neeraj2708** [fedberry/fedberry#24]
Hello all , I just want to ask about ssh login in fedberry-minimal-23.2-test1.raw.xz installed in Raspberry Pi 3 , I am unable to login via ssh on "root" user with password "fedberry" and also via "raspberry" user with password "raspberry" , then how can i login in my fedberry os ???
Please help , i also tried to google and also read stuff in fedberry.org but found nothing regarding this.
![screenshot from 2016-05-18 11-57-04](https://cloud.githubusercontent.com/assets/19423408/15349335/b4e5d51e-1cef-11e6-8bcc-eb6f755a4ce1.png)

**Comment by Gormartsen** [comment]
Hi!

Please use mini (not minimal) to have preconfigured root pass as mentioned in doc.

Minimal require HDMI screen to setup password on first boot

**Comment by Neeraj2708** [comment]
ok , Thank you :+1:
