### ISSUE TITLE
I follow the guide to boot fedberry,however there is no response of the display

### ISSUE THREAD

**Issue by zfyseu** [fedberry/fedberry#26]
Hello everyone!
I follow the guide to boot fedberry to the SD card, and I put the sd card into raspberry pi 2B,however there is no response of the display.
I think it has something to do with the config.txt.
But I don't how to change the config.txt.
How to solve the problem?
Thank you!

**Comment by agrez** [comment]
Hi zfyseu

Firstly, is the RPi2 booting up correctly? We need some additional information / clues to start helping you out.

The following is a good guide for trouble shooting boot problems with RPi's.
http://elinux.org/R-Pi_Troubleshooting

It might give you/us some hints as to what the problem might be.

**Comment by zfyseu** [comment]
Thank you,agrez!
when I power on the RPi, the red power led is on and the green led is flashing. But nothing on display.
How to solve it?
Thank you!

**Comment by zfyseu** [comment]
Hi,agrez!
I have solve the problem by editing the config.txt as following:

disable_overscan=1
hdmi_force_hotplug=1
hdmi_group=2
hdmi_mode=16
config_hdmi_boost=4
hdmi_ignore_edid=0xa5000080

Thank you anyway!

**Comment by agrez** [comment]
ok, glad to hear you found the problem. Will close this bug report then.
