### ISSUE TITLE
Issues with wireless - Edimax EW-7811Un

### ISSUE THREAD

**Issue by kenthua** [fedberry/fedberry#28]
I was having issues using nmcli to connect to my wireless AP.  Either I'm doing something wrong or I missed the documentation somewhere.

First I had to install the `NetworkManager-wifi` package.

Then I was able to issue the various `nmcli dev wifi` commands.

**Comment by agrez** [comment]
Hi Kenthua

What release did you download and use? For our previous release, NetworkManager-wifi was intentionally not included in our 'mini' release but should be available in all other releases.

**Comment by kenthua** [comment]
Thanks for the response @agrez .  That would be the reason why I had to manually install it myself then.   I am currently using the `mini` version.  `fedora-23-remix-rpi2-mini-1`
