### ISSUE TITLE
Unable to set max_usb_current=1 in /boot/config.txt

### ISSUE THREAD

**Issue by Tico06** [fedberry/fedberry#29]
Hi There,

I try to follow the following tutorial to increase current on USB port:
http://www.htpcguides.com/power-2-5-hard-drive-with-raspberry-pi-b/

With no chance. Is this setting taken into account ?

thanks and regards,

Eric.

**Comment by agrez** [comment]
Hi Eric. 

The config option used to work for me as I had /home /var mounted on an external usb HD for all the rpm building I was doing (ie I don't want to kill my SD cards with all that compiling). However I switched to using a usb thumb drive for the job (its faster and consumes way less power) and haven't needed it for about 5 months or so. I will re-test today and see if the option still works for me.

Best Regards
Vaughan

**Comment by Tico06** [comment]
Hi Vaughan,

Thanks for your support. In parallel, I have orderd a new power supply as the one used delivers 1.5amp, may be it's a bit short.

Regards, Eric.
-
_/) Eric Grammatico.

23 juillet 2016 06:40 "Vaughan Agrez"  a écrit:
	Hi Eric.

	The config option used to work for me as I had /home /var mounted on an external usb HD for all the rpm building I was doing (ie I don't want to kill my SD cards with all that compiling). However I switched to using a usb thumb drive for the job (its faster and consumes way less power) and haven't needed it for about 5 months or so. I will re-test today and see if the option still works for me.

	Best Regards
Vaughan

**Comment by agrez** [comment]
Hi Eric

I didn't quite get around to complete my testing but with my RPi3 I found my external usb HD worked with or without max_usb_current=1. I did some more searching and found some unofficial comments stating that RPi3's now provide 1200 mA by default to share across usb ports, so apparently max_usb_current=1 is redundant for this model.

As for the RPi2, I haven't tested it yet but for sure if you are running high power usb devices like external usb HD's you will need at least a 2 A power supply (2.5 A for the RPi3).

Regards
Vaughan

**Comment by Tico06** [comment]
Hi Vaughan,

Ok, thanks. Once I have received the power supply, I'll test and keep you updated.

Regards

Eric.
-
_/) Eric Grammatico.

27 juillet 2016 02:39 "Vaughan Agrez"  a écrit:
	Hi Eric

	I didn't quite get around to complete my testing but with my RPi3 I found my external usb HD worked with or without max_usb_current=1. I did some more searching and found some unofficial comments stating that RPi3's now provide 1200 mA by default to share across usb ports, so apparently max_usb_current=1 is redundant for this model.

	As for the RPi2, I haven't tested it yet but for sure if you are running high power usb devices like external usb HD's you will need at least a 2 A power supply (2.5 A for the RPi3).

	Regards
Vaughan

**Comment by Tico06** [comment]
Hi Vaughan,

I have finally received my power supply. It works like a charm.

Thanks and regards,

Eric.

**Comment by agrez** [comment]
Thanks for letting us know Tico06! Will close this issue now.
