### ISSUE TITLE
Fedberry 25: no release image file

### ISSUE THREAD

**Issue by simendeev** [fedberry/fedberry#35]
Hello. No release image file found at url  http://download.fedberry.org/?dir=releases/25/images/armhfp
Where can I download a file?
Thank you.

**Comment by agrez** [comment]
Hi @simendeev,

Whilst I have built F25 images internally, I have not made any publicly available as yet. I still have to spend some time adding some of our own selinux policies to allow the images to work correctly when selinux is enabled. Spare time has also been limited for me over the past few months, which isn't helping.

In the meantime you can always use the official Fedora 25 images (I would have thought most people would have switched over by now). :-)

Regards
Vaughan

**Comment by agrez** [comment]
ok, I have pushed up some initial barebone and minimal release images. XFCE and LXQt images to following when I get some more time.

**Comment by agrez** [comment]
xfce image is up! That was quicker than I thought it would be :-) LXQt image will take a while longer as I have to update a few packages.
