### ISSUE TITLE
Connect with usb

### ISSUE THREAD

**Issue by Jermorin** [fedberry/fedberry#36]
Hi guys ! 

I want to connect my Rpi3 by usb on my laptop (Fedora 25), 

Have you got some ideas about how can i ssh the rpi by usb ? 

Thanks a lot for fedberry :) 

Freedomly

**Comment by agrez** [comment]
Hi @Jermorin 
Its possible with the RPi Zero but I'm fairly sure its not possible with RPi2/3's (USB Hub/LAN chip is in the way for OTG mode). If others have a solution, please chime in.

**Comment by Jermorin** [comment]
Hi @agrez, Thx for answer. 

My goal : being to be able to use it without a local network, you have perhaps an idea on how I can connect it directly on my laptop by ethernet? How can I use the headless mode between two ethernet ports?

**Comment by agrez** [comment]
Hi @Jermorin 
You should be able to use a crossover ethernet cable to connect your RPi to your PC. Googling this seems to give a few howtos / examples. You will need to enable [headless mode](https://github.com/fedberry/fedberry-headless) on the RPi (if using the 'minimal' release). Leave the /boot/headless file empty (as I just saw a bug I have to fix).

For now (until I fix the headless mode bug), you will also need to manually add an appropriately configured /etc/sysconfig/network-scripts/ifcfg-eth0 file [(here's an example)](https://github.com/fedberry/fedberry/files/798307/ifcfg-eth0.txt) before booting the RPi for the first time.

**Comment by Jermorin** [comment]
Thanks a lot :+1: !
