### ISSUE TITLE
Error: Failed to synchronize cache for repo 'fedberry'

### ISSUE THREAD

**Issue by sbadux** [fedberry/fedberry#38]
Hello,
I can't update or install any program on my RPi2 with Fedberry. Every time that I run "yum update" or "yum install" I get:

Error: Failed to synchronize cache for repo 'fedberry'

I've tried to run 
"dnf clean all" and "dnf distro-sync --refresh" but without success

I'm using Fedberry 27. Any help? Thanks

**Comment by agrez** [comment]
Thanks for the bug report sbadux. Seems our fedberry Sourceforge mirror is misbehaving (it has been troublesome for some weeks now). I will demote the Sourceforge mirror in our fedberry mirrorlists and hopefully it will fix the issue.

**Comment by sbadux** [comment]
Thanks very much for your work. I'm really happy with Fedberry, after struggling with many other buggy Rpi-distros.
I have to modify something on my Fedberry installation or it will work automatically?

**Comment by agrez** [comment]
Nope, you won't have to do anything. It seems to have fixed the issue on all of my test installs. Let me know if it doesn't work for you.

**Comment by sbadux** [comment]
Yes! Now it works fine. Thanks!

**Comment by agrez** [comment]
Thanks, much appreciated. I'll look into that redirect when I get a spare moment. Closing this issue.
