### ISSUE TITLE
Torrents can't connect / really slow

### ISSUE THREAD

**Issue by sbadux** [fedberry/fedberry#39]
Hello,
I'm using my Raspberry Pi 2 as a torrent box to seed 24/7 some linux distro torrents that I've created. Nothing illegal.
I see that my torrents are really slow or don't connect at all with others peers. 

I share the same torrents from my Raspberry (Fedberry 27) and from my PC (Ubuntu 17.10) under the same LAN. The torrents on Ubuntu are seeding fine while the torrents on Fedberry doesn't seed at all or for only few seconds. I've tried to disable firewalld but with no success.

Same torrents, same network, same router. Any idea? I can't figure out if this is a fedberry issue (like it seems to me) or not...

**Comment by sbadux** [comment]
After disabling the firewalld and REBOOTING it seems faster. I think I get less peers than Ubuntu but on Ubuntu I use Tixati while the Raspberry is running Qbittorrent. Anyway, it doesn't seem some kind of bug of Fedberry but a wrong configiuration. I'm closing this issue, sorry

**Comment by agrez** [comment]
Hi Sbadux. Out of interest I just did a quick test under Fedberry using 'transmission' and quickly came to the same conclusion as you (it basically wouldn't seed to any peers at all!). After scratching my head and looking at lots of logs, I couldn't find anything obvious. I then switched to using 'deluge' and it seems to seed just fine.

**Comment by sbadux** [comment]
Thanks for the test you have made and for the reply. 
I can't understand at all what's happening. qbittorrent seems to work fine but not as well as Tixati. For example, I have a peer on Tixati which is downloading a torrent and doesn't appears on qbittorrent. If I do a "Add peer" on qbittorrent the new peer is added but it disconnects after 1 second. 
This behavior can be due to the different torrent client I use, but I'm not so sure because the same happens with Transmission or Deluge on Fedberry. I'll eventually reopen the issue if I find something specific to Fedberry, but there are a lot of possibilities...
