### ISSUE TITLE
safe to use Fedora's bcm434xx module?

### ISSUE THREAD

**Issue by knight-of-ni** [fedberry/fedberry#42]
Recently Fedora started to include the bcm434xx module in the linux-firmware package. This conflicts with the same module included with the FedBerry bcm434xx-firmware package.

Normally, I'd just try it and find out, but one particular Fedberry deployment of mine is remote, so I don't want to simply assume there won't be any problems.

Can anyone confirm that this package conflict can indeed be resolved simply by issuing `dnf remove bcm434xx-firmware; dnf update`?

Here is the relevant error text from dnf update:
```
Is this ok [y/N]: y
Downloading Packages:
linux-firmware-20181008-88.gitc6b6265d.fc28.noa 2.3 MB/s |  73 MB     00:31    
--------------------------------------------------------------------------------
Total                                           2.2 MB/s |  73 MB     00:32     
Running transaction check
Transaction check succeeded.
Running transaction test
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: Transaction check error:
  file /usr/lib/firmware/brcm/brcmfmac43455-sdio.bin from install of linux-firmware-20181008-88.gitc6b6265d.fc28.noarch conflicts with file from package bcm434xx-firmware-20181010-1.b518de4.fc28.noarch

Error Summary
-------------
```

**Comment by knight-of-ni** [comment]
And I found the problem.

Sitting in /etc/yum.repos.d were several fedora repo files with an rpmnew extension. Inside the new repo files was an exclude statement, excluding the linux-firmware package from Fedora.

That's the clue I needed to tell me I should stick with the bcm434xx-firmware package from Fedberry. Closing...

**Comment by agrez** [comment]
Yep, you worked it out. :-) I've had a few 'issues' in regards to this in the past few months. I might look at gaining a bit more control over the fedora*.repo files when updating rpms to avoid these types of problems.

I would prefer not to ship our own modified linux-firmware package but having the bcm434xx-firmware rpm allows us to more easily update RPi specific firmware when required (eg. upstream linux-firmware does not necessarily carry the latest firmware releases).
