### ISSUE TITLE
RPMFusion just announced rpi namespace

### ISSUE THREAD

**Issue by knight-of-ni** [fedberry/fedberry#44]
I just saw this message come up on the RPMFusion developers list, and I thought you might be interested:
https://lists.rpmfusion.org/archives/list/rpmfusion-developers@lists.rpmfusion.org/thread/COSRHFIEI4EZYVSBGEINAMNUCOTEUWMC/

So it seems RPMFusion is jumping on the rpi hw accel bandwagon. 
At the end of his message, Nicolas made it know that he is looking for help with the packaging work for this namespace.

Perhaps there is an opportunity for FedBerry to coordinate with RPMFusion on some level here. 
This is just a thought. I'm certainly not trying to dictate policy, but it might be worth a conversation with those guys. If I can find a way to plug in, I could certainly help as well.

**Comment by agrez** [comment]
Interesting indeed. Thanks for the heads up! It would indeed make my job easier if they could make some rpi specific packages available. I'm wondering if they know about the existence of Fedberry? If not, someone needs to point them towards our github repos so they can take a look around. They might find some useful tips/tricks which will aid them in their endeavour.

**Comment by leigh123linux** [comment]
I've had a quick look a ffmpeg and mpv packages, anything from unitedrpms isn't acceptable for rpmfusion as their packaging is inferior and doesn't meet current fedora guidelines.
Also unitedrpms stole our work and have claimed credit for it, they are cheap knockoff bastards.

Faults in mpv are:

1. It bundles ffmpeg.
2. It bundles libass.
3. It bundles waf.
4. Has obsolete mime scriplets.
5. Has  obsolete ldconfig scriptlets.
6. Source URL and use of git snapshot are wrong for a stable release.

ffmpeg has similar faults.

P.S Sorry for the harsh tone.

**Comment by agrez** [comment]
Welcome! I too could probably randomly pop up somewhere and start pointing out Fedora packaging guidelines irregularities in spec files but I tend to find that this practise doesn't cultivate much of a positive, constructive relationship going forward. Anyhow, last I checked, we are NOT Fedora and we don't have to abide by their packaging guidelines (not that I'm against their guidelines mind you, they are definitely needed in such a large complex organisation).

I have never worked with and have no idea about any animosity between rpmfusion and unitedrpms but it sure sounds like something I don't want to be involved with. Sticking my hands in a hornets nest is not high on the list of priorities in my life. I was under no illusion that rpmfusion would be actually forking our specs as I know they already package ffmpeg and mpv. It would make far more sense just to tweak your own specs, as they are familiar to those who have been previously working on them.

**Comment by kwizart** [comment]
RPM Fusion is a collective work and you are welcomed to contribute to.
It would be unfortunate that you stay away from our project related to the rpi.
Please remind that any patches are welcomed.

The aim of RPM Fusion is to build a complement repository for Fedora, RHEL and derivates. It was built from the idea that many single featured or personal repositories are not sustainable for end-users, because that is well known to have conflicts and breaks.

The only way forward is to consolidate as a single community with a common guidelines. 
Anyone feel free to join our mailing-list if interested:
https://lists.rpmfusion.org

**Comment by agrez** [comment]
Good philosophy, thanks for your input. I will join some rpmfusion mailing lists and follow along for a while. Remember, I come from outside the Fedora development ecosystem, so I still have a lot to learn if I am to help out at some point in the future.
