### ISSUE TITLE
CPU1 Failed to come online

### ISSUE THREAD

**Issue by sbadux** [fedberry/fedberry#45]
Hello,
I've updated Fedberry and after that it can't boot becasue of this error:
CPU1: Failed to come online

![error](https://user-images.githubusercontent.com/28478027/58373857-12634280-7f35-11e9-9427-85138c7a669b.jpg)

The error is related to one of the following updates (these are the updates I've installed with DNF udpate):

Installing:
 kernel                       armv7hl 4.19.36-1.rpi.fc29        fedberry   18 k
 kernel-core                  armv7hl 4.19.36-1.rpi.fc29        fedberry   12 M
 kernel-modules               armv7hl 4.19.36-1.rpi.fc29        fedberry  7.3 M
 kernel-modules-extra         armv7hl 4.19.36-1.rpi.fc29        fedberry  1.3 M
Upgrading:
 bcm434xx-firmware            noarch  20190420-1.b518de4.fc29   fedberry  594 k
 bcmstat                      noarch  0.5.1-1.cbd2fd5.fc29      fedberry   34 k
 Thunar                       armv7hl 1.8.4-5.fc29              updates   1.4 M
 coreutils                    armv7hl 8.30-7.fc29               updates   833 k
 coreutils-common             armv7hl 8.30-7.fc29               updates   1.9 M
 daxctl-libs                  armv7hl 65-1.fc29                 updates    30 k
 ethtool                      armv7hl 2:5.0-1.fc29              updates   132 k
 exo                          armv7hl 0.12.5-1.fc29             updates   615 k
 gdb-headless                 armv7hl 8.2-7.fc29                updates   2.7 M
 glibc                        armv7hl 2.28-30.fc29              updates   3.0 M
 glibc-all-langpacks          armv7hl 2.28-30.fc29              updates    25 M
 glibc-common                 armv7hl 2.28-30.fc29              updates   672 k
 glibc-langpack-en            armv7hl 2.28-30.fc29              updates   817 k
 glibc-langpack-it            armv7hl 2.28-30.fc29              updates   491 k
 gnome-desktop3               armv7hl 3.30.2.3-1.fc29           updates   540 k
 gstreamer1-plugins-ugly-free armv7hl 1.14.4-2.fc29             updates    88 k
 hwdata                       noarch  0.323-1.fc29              updates   1.5 M
 libdnf                       armv7hl 0.31.0-3.fc29             updates   469 k
 libertas-usb8388-firmware    noarch  2:20190514-96.fc29        updates    93 k
 libicu                       armv7hl 62.2-1.fc29               updates   8.5 M
 libmodulemd1                 armv7hl 1.8.10-1.fc29             updates   157 k
 libnice                      armv7hl 0.1.16-3.fc29             updates   151 k
 librsvg2                     armv7hl 2.44.14-1.fc29            updates   1.0 M
 libsmbclient                 armv7hl 2:4.9.8-0.fc29            updates    63 k
 libwbclient                  armv7hl 2:4.9.8-0.fc29            updates    39 k
 libxcrypt                    armv7hl 4.4.6-1.fc29              updates   132 k
 libzstd                      armv7hl 1.4.0-1.fc29              updates   203 k
 linux-firmware-whence        noarch  20190514-96.fc29          updates    32 k
 m17n-lib                     armv7hl 1.8.0-3.fc29              updates   159 k
 ndctl                        armv7hl 65-1.fc29                 updates   152 k
 ndctl-libs                   armv7hl 65-1.fc29                 updates    59 k
 nmap-ncat                    armv7hl 2:7.70-5.fc29             updates   180 k
 pcre2                        armv7hl 10.33-2.fc29              updates   217 k
 perl-Errno                   armv7hl 1.29-431.fc29             updates    24 k
 perl-IO                      armv7hl 1.39-431.fc29             updates    88 k
 perl-interpreter             armv7hl 4:5.28.2-431.fc29         updates   6.3 M
 perl-libs                    armv7hl 4:5.28.2-431.fc29         updates   1.5 M
 perl-macros                  armv7hl 4:5.28.2-431.fc29         updates    19 k
 python3-hawkey               armv7hl 0.31.0-3.fc29             updates    68 k
 python3-libdnf               armv7hl 0.31.0-3.fc29             updates   501 k
 rsyslog                      armv7hl 8.1904.0-1.fc29           updates   602 k
 samba-client                 armv7hl 2:4.9.8-0.fc29            updates   487 k
 samba-client-libs            armv7hl 2:4.9.8-0.fc29            updates   4.2 M
 samba-common                 noarch  2:4.9.8-0.fc29            updates   140 k
 samba-common-libs            armv7hl 2:4.9.8-0.fc29            updates    85 k
 selinux-policy               noarch  3.14.2-59.fc29            updates   115 k
 selinux-policy-targeted      noarch  3.14.2-59.fc29            updates    14 M
 vpnc                         armv7hl 0.5.3-34.svn550.fc29      updates    78 k
 xfce4-places-plugin          armv7hl 1.8.0-1.fc29              updates    95 k
 xfwm4                        armv7hl 4.13.1-8.fc29             updates   597 k

**Comment by agrez** [comment]
Thanks for reporting this sabdux. I haven't been able to reproduce the error on any of my RPi's. What model RPi are you using?

**Comment by sbadux** [comment]
> Thanks for reporting this sabdux. I haven't been able to reproduce the error on any of my RPi's. What model RPi are you using?

Hello, I'm using a Raspbery Pi 2 B

**Comment by agrez** [comment]
I tested against my RPi 2B's and also didn't hit the issue. Have you tried booting from one of the other previously installed kernels?

**Comment by sbadux** [comment]
> I tested against my RPi 2B's and also didn't hit the issue. Have you tried booting from one of the other previously installed kernels?

Now I've restored a previous SD image, but I'll try to update again. How can i boot from a previous kernel?

EDIT: after some test, I've tried to update all the packaget, except the kernel. Then I've updated also the kernel. Now seems to work. Please keep this issue in standby and I'll let you know in 24 if it works also on my normal SD image.

**Comment by agrez** [comment]
ok, good to hear.

If the system is unbootable, you can pull out the sdcard in the RPi and mount the boot partition in another PC. You then manually copy one of the previously used kernels sitting in the boot partition and rename it to 'kernel7.img' (this will overwrite the existing kernel7.img). Eg.
`cp vmlinuz-4.19.30-1.rpi.fc29.armv7hl kernel7.img`

Then unmount the boot partition and insert the sdcard back into your RPi. As long as device trees between kernel releases haven't change too much, this should give you a bootable system back. Once you boot back into the system run fedberry-config to finish the job properly by going to System--->Set Boot Kernel, then select the older kernel again which will copy over the correct corresponding device tree blobs and overlays to match the selected kernel.

**Comment by sbadux** [comment]
Hello,
I can confirm that everything works fine now. I've updated the other packages first and then the kernel.

Sorry for the wrong bug report, I'll try at least twice before open an issue in the future :)

**Comment by agrez** [comment]
No need to apologise. There must have been a legitimate issue, we just didn't work it out. There are many other factors they may have caused or contributed to it.

**Comment by knight-of-ni** [comment]
This sounds slightly similar to an issue I was experiencing on three different different rpi 2/3's. 

At some point in the Fedora/Fedberry 28 lifecycle, all three of my pi's would segfault very early in the boot process. It did this almost every time after a distro upgrade, frequently did it after a kernel upgrade, and did it after about every 2 or 3 normal reboots when not upgrading anything. Most of the time it was a segfault, but I seem to recall at least once seeing "CPU not online" message.

Since it didn't happen all the time and since two of the three pi's were remote, one can imagine how hard it was to isolate the cause.

To make a long story short, it was the gpu_mem = 16 (which I set on all my headless pi's), that was causing the problem. At some point in the normal Fedora upgrade cycle, gpu_mem = 32, became the new minimum. If you've got gpu_mem set to 16, the pi will sometimes boot.

Since I didn't intentionally reboot all that often (and all my equipment is on a ups), I lived with this for over a year before discovering how to fix this.

Don't know if that helps the OP, but I thought I'd throw this out there. I'm sure I am not the only one who has set gpu_mem = 16, in an attempt to squeeze as much memory as possible out of the pi.

**Comment by agrez** [comment]
Thanks for your input here Andrew. Yes, I noticed this at the end of last year too, so I nuked the 16mb option from fedberry-config but I don't recall the error messages I was getting at the time (I should have been more descriptive in my git commit I suppose).

https://github.com/fedberry/fedberry-config/commit/90af85561864ccc7042d567f8e2984d5b802a76b
