### ISSUE TITLE
Fedberry web site (and package mirror) down

### ISSUE THREAD

**Issue by speachy** [fedberry/fedberry#47]
Fedberry.org takes me to a parking/error page on webnames.ru

And the package mirror URL (via fedberry.github.io) takes me to a '500' error page, also on webnames.ru

**Comment by agrez** [comment]
Yes, it seems the domain registration has expired. I will chat to @Gormartsen and see if he will renew. FOr the time being, we have ceased development of Fedberry, however I would like to keep the domain name for a while longer.

**Comment by agrez** [comment]
Issue is resolved.
